fluent/src/androidMain/kotlin/com/konyaco/fluent/defaultFontFamily.android.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/DefaultFontFamily.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/FluentTheme.kt, fluent/src/jvmMain/kotlin/com/konyaco/fluent/defaultFontFamily.desktop.kt
Load Segeo UI Variable Font as the defaultFontFamily when desktop system contain the font. which make control more consistent with Windows 11.
Screenshot
=> Segeo UI variable

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SideNav.kt
SideNavItem' indicator animation implementation.
https://user-images.githubusercontent.com/26089739/235692706-07fcd200-7517-4158-8a3d-753846f6ebe8.mp4
=> [Navigation] SideNavItem' indicator animation implementation

fluent/src/androidMain/kotlin/com/konyaco/fluent/PlatformCompositionLocalProvider.android.kt, fluent/src/androidMain/kotlin/com/konyaco/fluent/component/FontIcon.android.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/FluentTheme.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/PlatformCompositionLocalProvider.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Dropdown.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/FontIcon.kt, fluent/src/jvmMain/kotlin/com/konyaco/fluent/PlatformCompositionLocalProvider.desktop.kt, fluent/src/jvmMain/kotlin/com/konyaco/fluent/component/ContextMenu.desktop.kt, fluent/src/jvmMain/kotlin/com/konyaco/fluent/component/FontIcon.desktop.kt
1. Before
2. After
1. Requirement: JVM platfrom and installed `Segoe Fluent Icons` font.
=> Fluent context menu

fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Layer.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Button.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/CheckBox.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/RadioButton.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SideNav.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Slider.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TextField.kt
According to the [document](https://developer.android.com/jetpack/compose/custom-modifiers#create_a_custom_modifier_using_a_composable_modifier_factory).
=> Remove `Modifier.composed`

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Button.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/CheckBox.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/MenuFlyout.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/RadioButton.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/RatingControl.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SideNav.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Switcher.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TextField.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/scheme/VisualStateScheme.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/App.kt
1. ButtonColorScheme
2. CheckBoxColorScheme
3. MenuItemColorScheme
4. RadioButtonStyleScheme
5. NavigationItemColorScheme, `NavigationItem.Indicator` and `NavigationDefaults.VerticalIndicator`
6. SwitcherStyleScheme
7. TextFieldColorScheme, `TextField.placeholder`, `TextFieldDefaults.DecorationBox`
=> [fluent] style migration: visual state scheme migration

README.md, build-plugin/src/main/java/com/konyaco/fluent/plugin/build/BuildConfig.kt, gradle/libs.versions.toml
I'm considering to release dev8, because the compose 1.6.10 is an important update. What do you think?
=> Bump to compose 1.6.10

gallery/build.gradle.kts, gallery/src/androidMain/kotlin/com/konyaco/fluent/gallery/MainActivity.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/App.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/ComponentGroupInfo.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/ComponentNavigator.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/Main.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/ComposeWindowProcedure.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/SkiaLayerWindowProcedure.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/User32Extend.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/WindowProcedure.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/structure/VersionHelper.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/structure/WinUserConst.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/structure/WindowMargins.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/window/LayoutHitTestOwner.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/window/WindowsWindowFrame.kt, gradle/libs.versions.toml
1. Android support navigate back.
2. Windows 11 has MicaEffect and new title bar experience which looks like UWP's ExtendToTitleBar API effects.
**reference**: 
[TransparentDecorationWindowProc](https://github.com/lhwdev/compose-window/blob/main/modules/platform/windows/src/main/kotlin/com/lhwdev/compose/window/platform/windows/TransparentDecorationWindowProc.kt)
[win32-window-custom-titlebar](https://github.com/grassator/win32-window-custom-titlebar)
[Missing animations when minimizing/maximizing/restoring undecorated window](https://github.com/JetBrains/compose-multiplatform/issues/3388#top)
https://github.com/Konyaco/compose-fluent-ui/assets/26089739/12891758-a1b1-46b5-bf8b-36dfa2652fdc
=> [gallery] UI Improve.

fluent/src/androidMain/kotlin/com/konyaco/fluent/background/Elevation.android.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Elevation.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Layer.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Dropdown.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Flyout.kt, fluent/src/desktopMain/kotlin/com/konyaco/fluent/background/Elevation.desktop.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/design/ElevationScreen.kt
`Modifier.elevation()`
```kotlin
val elevation = ElevationDefaults.flyout
Layer(
elevation = elevation,
backgroundSizing = BackgroundSizing.InnerBorderEdge,
border = BorderStroke(
width = 1.dp,
color = when {
elevation.value > 2f -> FluentTheme.colors.stroke.surface.flyout
elevation.value in 0f..1f -> FluentTheme.colors.stroke.card.default
else -> Color.Transparent
}
),
color = FluentTheme.colors.background.solid.quaternary
)
```
1.Flyout
2.Dropdown
3.Gallery
=> [fluent] `Elevation` support

fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Layer.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Expander.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/GallerySection.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/collections/ExpanderScreen.kt
1. `Expander`
2. `ExpanderItem`
3. `ExpanderItemSeparator`
4. `CardExpanderItem`
```Kotlin
val expanded = remember { mutableStateOf(false) }
Expander(
expanded = expanded.value,
onExpandedChanged = { expanded.value = it },
heading = { Text("Power button functionality") },
caption = { Text("Adjust what yor power buttons control") },
icon = { Icon(Icons.Default.Power, null) },
training = {
val checked = remember { mutableStateOf(true) }
Switcher(
checked = checked.value,
{ checked.value = it },
textBefore = true,
text = if (checked.value) "On" else "Off"
)
}
) {
ExpanderItem(
heading = { Text("When I press the power button on battery") },
training = { DropDownButton(onClick = {}, content = { Text("Sleep") }) }
)
ExpanderItemSeparator()
ExpanderItem(
heading = { Text("When I press the power …
```
=> [fluent] Add `Expander` and `ExpanderItem`.

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Button.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/LiteFilter.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/basicinput/LiteFilterScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/basicinput/PillButtonScreen.kt
1. `PillButton`
2. `ListFilter`
```Kotlin
val selectedItem = remember { mutableStateOf("") }
LiteFilter {
items().forEach { name ->
PillButton(
selected = selectedItem.value == name,
onSelectedChanged = {
if (selectedItem.value != name) {
selectedItem.value = name
} else {
selectedItem.value = ""
}
},
) {
Text(name)
}
}
}
```
=> [fluent] Add `PillButton` and `LiteFilter`.

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Button.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SegmentedControl.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/basicinput/SegmentedControlScreen.kt
1. `SegmentedControl`
2. `SegmentedButton`
```Kotlin
val checkedIndex = remember { mutableStateOf(0) }
SegmentedControl {
repeat(count) { index ->
SegmentedButton(
checked = index == checkedIndex.value,
onCheckedChanged = { checkedIndex.value = index },
position = when (index) {
0 -> SegmentedItemPosition.Start
count - 1 -> SegmentedItemPosition.End
else -> SegmentedItemPosition.Center
},
text = { Text("Text") }
)
}
}
```
=> [fluent] Add `SegmentedControl` and `SegmentedButton`.

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TabView.kt, gallery/src/androidMain/kotlin/com/konyaco/fluent/gallery/screen/navigation/TabViewScreen.android.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/navigation/TabViewScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/settings/SettingsScreen.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/screen/navigation/TabViewScreen.desktop.kt
1. `TabRow`
2. `TabItem`
Style: 1. InContentArea(default)  2. InTitleBar
```Kotlin
val selectedKey = remember { mutableIntStateOf(0) }
val items = remember { mutableStateListOf(*Array(10) { it }) }
val state = rememberLazyListState()
val endDividerController = rememberTabItemEndDividerController(
selectedKey = { selectedKey.value },
state = state
)
TabRow(
state = state,
selectedKey = { selectedKey.value },
modifier = Modifier.fillMaxWidth()
) {
itemsIndexed(items, key = { _, item -> item }) { index, item ->
val interactionSource = remember { MutableInteractionSource() }
TabItem(
selected = item == selectedKey.value,
onSelectedChanged = { selectedKey.value = item },
endDividerVisible = endDividerController.attach(item, interactionSource),
interactionSource = interactionSource,
text = …
```
=> [fluent] Add `TabView`.

fluent/src/commonMain/kotlin/com/konyaco/fluent/Colors.kt
This commit introduces system colors for Fluent UI components. These colors are used for attention, success, caution, critical, and neutral states.
The colors are generated based on the dark mode setting and provide both solid and background variants.
=> [fluent] feat: Implement system colors

gradle/libs.versions.toml
This commit updates the Haze dependency version to 1.0.2.
=> [gallery] chore(deps): Update Haze to 1.0.2

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TabView.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/navigation/TabViewScreen.kt
This commit fixes an issue where the `TabView` content could exceed its bounds, potentially causing layout issues.
The fix involves wrapping the content with `wrapContentWidth(Alignment.Start)`, ensuring that the content is constrained within the available width and aligned to the start. This prevents overflow and maintains the intended layout.
=> [fluent] Fix: Prevent TabView from exceeding its bounds

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/MenuBar.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/MenuFlyout.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/menus/MenuBarScreen.kt
This commit introduces the `MenuBar` component, a horizontal menu bar typically used at the top of a window or application to provide access to various commands and options.
It supports `MenuBarItem`s that can open `MenuFlyout`s. Also adds `OverflowMenuBar` component that will automatically handle overflow items by moving them to a separate popup.
The `MenuBar` and `OverflowMenuBar` manage their menu items and popups state, and provides default color schemes for menu items.
=> [fluent] feat: Implement MenuBar component

fluent/src/commonMain/kotlin/com/konyaco/fluent/Colors.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Badge.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/BadgeIcons.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/InfoBar.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/NavigationView.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Severity.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SideNav.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TopNav.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/status/BadgeScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/status/InfoBarScreen.kt
This commit introduces the `InfoBar` componentan inline message to display app-wide status changes.It provides options to:
- display a title and message
- display different severities: informational, success, warning, and critical
- show or hide an icon and close action button
- add a custom action button or hyperlink.It supports different background colors, content colors, and icon colors based on the specified severity level.This commit also includes the `InfoBarColors` class for customising the InfoBar's color scheme and the `Severity` enum for the different severity level.
This commit introduces the `Badge` component, a non-intrusive UI element for displaying notifications or highlighting areas within an application.
- It supports different statuses (Informational, InformationalSafe, …
=> [fluent] feat: Add InfoBar and Badge component

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SelectorBar.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/navigation/SelectorBarScreen.kt
This commit introduces the `SelectorBar` component, a control that lets a user switch between a small number of different sets or views of data. It supports an icon and text, and it's intended to present a limited number of options.
=> [fluent] Add `SelectorBar` component

fluent/src/commonMain/kotlin/com/konyaco/fluent/Colors.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Elevation.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Layer.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/CopyButton.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/design/ColorScreen.kt
1. Add Design Guide/ColorScreen.
2. Aliging some color name with Design Toolkit.
3. Update color system values.
4. Add ColorOnImageFill Colors.
5. Add FocusBorder Stroke.
=> [Color] Update Color System & Add Design Guide/ Color

fluent/src/androidMain/kotlin/com/konyaco/fluent/component/Flyout.android.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/AutoSuggestBox.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/ColorPicker.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Flyout.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/MenuFlyout.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/NavigationView.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/SideNav.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Slider.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TooltipBox.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/TopNav.kt, fluent/src/skikoMain/kotlin/com/konyaco/fluent/component/Flyout.skiko.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/App.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/CopyButton.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/GalleryHeader.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/basicinput/SliderScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/status/TooltipScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/text/AutoSuggestBoxScreen.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/window/WindowsWindowFrame.kt
1. Add `FlyoutAnchorScope`.
2. Add `TooltipBox`
=> [fluent] Add `TooltipBox` and `FlyoutAnchorScope`

fluent/src/commonMain/kotlin/com/konyaco/fluent/background/Layer.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/FlipView.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/GridViewItem.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/PipsPager.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/component/ComponentGroupInfo.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/collections/FlipViewScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/collections/GridViewItemScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/design/IconsScreen.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/scrolling/PipsPagerScreen.kt
This commit introduces the `GridViewItem` component, a selectable item template for grids.
- The `GridViewItem` supports single and multi-select modes, customizable colors, and overlay content. 
- It provides visual feedback for different states such as default, hovered, pressed, and disabled.Additionally, the commit includes a `MultiSelectGridViewItem` variant, that adds a checkbox as an overlay for multi-selection scenarios.
This commit introduces the `FlipView` component, a control that allows users to flip through a collection of items.
It provides two variations: `HorizontalFlipView` and `VerticalFlipView`, which enable horizontal and vertical flipping respectively.
The component utilizes `HorizontalPager` and `VerticalPager` from the Compose Pager library, and includes visual …
=> [fluent] feat: Implement GridViewItem ,FlipView and PipsPager component

fluent/src/commonMain/kotlin/com/konyaco/fluent/component/ColorPicker.kt, fluent/src/commonMain/kotlin/com/konyaco/fluent/component/Slider.kt, gallery/src/commonMain/kotlin/com/konyaco/fluent/gallery/screen/basicinput/SliderScreen.kt
1. Simplified the Slider API for most common usag. Use BasicSlider t customize slider.
2. Snap behavior and tickmark can be controlled seperately now.
=> Seperate slider to `Slider` and `BasicSlider`

gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/ComposeWindowProcedure.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/SkiaLayerWindowProcedure.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/User32Extend.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/structure/MenuItemInfo.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/jna/windows/structure/WinUserConst.kt, gallery/src/desktopMain/kotlin/com/konyaco/fluent/gallery/window/WindowsWindowFrame.kt
feat: Add window frame context menu and accent color support
This commit introduces several enhancements to the window frame:
-   **Context Menu:** Added
``````
a right-click context menu to the window frame, providing options to restore, move, size, minimize, maximize, and close the window.
-   **Accent Color Support:** Implemented support for the system's accent color in the window frame. The window frame now dynamically adapts to changes in the system'
``````
s color scheme.
-   **Caption Button Customization**: change caption buttons color to system accent color when enabled.
-   **Window Focus Indication:** Added visual feedback to indicate whether the window is in focus or not.
-   **Menu Item Management**: Implemented dynamic enabling and disabling of menu items based on the …
=> feat: Add window frame context menu and accent color support

gallery/proguard-rules.desktop.pro, gallery/src/desktopMain/kotlin/io/github/composefluent/gallery/jna/windows/ComposeWindowProcedure.kt, gallery/src/desktopMain/kotlin/io/github/composefluent/gallery/window/LayoutHitTestOwner.kt
1. Rmoved the reflect of LayoutNode .
2. Update Hit Test behavior that addresses an issue where hit test results could be incorrect after moving the window to a different monitor.
=> [gallery] Update windows title bar

fluent/src/commonMain/kotlin/io/github/composefluent/component/CalendarView.kt
A new optional parameter to the `CalendarDatePickerState` constructor. Users can now specify an initial `instant` (of type `kotlinx.datetime.Instant`) and `timeZone` (of type `kotlinx.datetime.TimeZone`) to set the starting date of the calendar.
If no values are provided, the calendar will default to the current system time and time zone, maintaining the previous behavior.
close #112
=> feat: Add initial date parameter to CalendarDatePickerState

fluent/src/commonMain/kotlin/io/github/composefluent/component/AutoSuggestBox.kt, fluent/src/commonMain/kotlin/io/github/composefluent/component/Dialog.kt, fluent/src/commonMain/kotlin/io/github/composefluent/component/Dropdown.kt, fluent/src/commonMain/kotlin/io/github/composefluent/component/Flyout.kt, fluent/src/commonMain/kotlin/io/github/composefluent/component/MenuFlyout.kt
The `focusable` parameter in PopupProperties controls certain interaction behaviors, particularly for components like Dialog, Flyout, and Dropdown. Previously, setting it to `false` allowed users to click the DropdownButton multiple times, which causes animation problems.
However, some components do require this behavior. For example, a `MenuBar` needs to be able to display a new menu immediately when the user hovers over another menu button.
So, I exposed this parameter, allows components to choose the expected behavior.
Meanwhile, adjusted the `focusable` setting for Dialog specifically, as Dialog components also need to handle keyboard interactions from users.
=> Add `focusable` parameter to `Flyout` and defaults to `true`
